[package]
name = "ex3_obc_cubics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
nix = "0.24"
tokio = { version = "1", features = ["full"] }


